
USE sucos;

ALTER TABLE tbcliente ADD PRIMARY KEY (CPF);

ALTER TABLE tbcliente ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO tbcliente (
CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,IDADE,SEXO,
LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA,DATA_NASCIMENTO) 
VALUES ('00388934505','VANDERLEIA CAVALCANTE','AV EVA PEREIRA DOS SANTOS 173','',
'MORRINHOS','GUARUJA','SAO PAULO','2222222',34,'F',10000.00, 2000,
0,'1988-05-02');

SELECT * FROM tbcliente;


